sonar.projectKey=SergioSanab_GanApp
sonar.organization=ganapp

# Solo analizar estas dos carpetas
sonar.sources=lib,functions
sonar.tests=test
sonar.exclusions=android/**,ios/**,build/**,web/**,linux/**,macos/**,windows/**,scripts/**
